// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/pubsub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubSubScope int32

const (
	PubSubScope_NONE             PubSubScope = 0
	PubSubScope_SEGMENT          PubSubScope = 1
	PubSubScope_PROJECT          PubSubScope = 2
	PubSubScope_ROOT             PubSubScope = 3
	PubSubScope_SEGMENT_AND_ROOT PubSubScope = 4
	PubSubScope_TO_ROOT          PubSubScope = 5
)

// Enum value maps for PubSubScope.
var (
	PubSubScope_name = map[int32]string{
		0: "NONE",
		1: "SEGMENT",
		2: "PROJECT",
		3: "ROOT",
		4: "SEGMENT_AND_ROOT",
		5: "TO_ROOT",
	}
	PubSubScope_value = map[string]int32{
		"NONE":             0,
		"SEGMENT":          1,
		"PROJECT":          2,
		"ROOT":             3,
		"SEGMENT_AND_ROOT": 4,
		"TO_ROOT":          5,
	}
)

func (x PubSubScope) Enum() *PubSubScope {
	p := new(PubSubScope)
	*p = x
	return p
}

func (x PubSubScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PubSubScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pubsub_proto_enumTypes[0].Descriptor()
}

func (PubSubScope) Type() protoreflect.EnumType {
	return &file_proto_pubsub_proto_enumTypes[0]
}

func (x PubSubScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PubSubScope.Descriptor instead.
func (PubSubScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Segment       string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	Project       string                 `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Ack           bool                   `protobuf:"varint,5,opt,name=ack,proto3" json:"ack,omitempty"`
	Sub           bool                   `protobuf:"varint,6,opt,name=sub,proto3" json:"sub,omitempty"`
	SubId         string                 `protobuf:"bytes,7,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	SubPod        string                 `protobuf:"bytes,8,opt,name=sub_pod,json=subPod,proto3" json:"sub_pod,omitempty"`
	SubModule     string                 `protobuf:"bytes,9,opt,name=sub_module,json=subModule,proto3" json:"sub_module,omitempty"`
	SubBroker     string                 `protobuf:"bytes,10,opt,name=sub_broker,json=subBroker,proto3" json:"sub_broker,omitempty"`
	SubProject    string                 `protobuf:"bytes,11,opt,name=sub_project,json=subProject,proto3" json:"sub_project,omitempty"`
	Scope         PubSubScope            `protobuf:"varint,12,opt,name=scope,proto3,enum=proto.PubSubScope" json:"scope,omitempty"`
	Context       []byte                 `protobuf:"bytes,13,opt,name=context,proto3" json:"context,omitempty"`
	Payload       []byte                 `protobuf:"bytes,14,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *Message) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Message) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *Message) GetSub() bool {
	if x != nil {
		return x.Sub
	}
	return false
}

func (x *Message) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *Message) GetSubPod() string {
	if x != nil {
		return x.SubPod
	}
	return ""
}

func (x *Message) GetSubModule() string {
	if x != nil {
		return x.SubModule
	}
	return ""
}

func (x *Message) GetSubBroker() string {
	if x != nil {
		return x.SubBroker
	}
	return ""
}

func (x *Message) GetSubProject() string {
	if x != nil {
		return x.SubProject
	}
	return ""
}

func (x *Message) GetScope() PubSubScope {
	if x != nil {
		return x.Scope
	}
	return PubSubScope_NONE
}

func (x *Message) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_pubsub_proto protoreflect.FileDescriptor

const file_proto_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x12proto/pubsub.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\x12\x18\n" +
	"\aproject\x18\x04 \x01(\tR\aproject\x12\x10\n" +
	"\x03ack\x18\x05 \x01(\bR\x03ack\x12\x10\n" +
	"\x03sub\x18\x06 \x01(\bR\x03sub\x12\x15\n" +
	"\x06sub_id\x18\a \x01(\tR\x05subId\x12\x17\n" +
	"\asub_pod\x18\b \x01(\tR\x06subPod\x12\x1d\n" +
	"\n" +
	"sub_module\x18\t \x01(\tR\tsubModule\x12\x1d\n" +
	"\n" +
	"sub_broker\x18\n" +
	" \x01(\tR\tsubBroker\x12\x1f\n" +
	"\vsub_project\x18\v \x01(\tR\n" +
	"subProject\x12(\n" +
	"\x05scope\x18\f \x01(\x0e2\x12.proto.PubSubScopeR\x05scope\x12\x18\n" +
	"\acontext\x18\r \x01(\fR\acontext\x12\x18\n" +
	"\apayload\x18\x0e \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x128\n" +
	"\ttimestamp\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*^\n" +
	"\vPubSubScope\x12\b\n" +
	"\x04NONE\x10\x00\x12\v\n" +
	"\aSEGMENT\x10\x01\x12\v\n" +
	"\aPROJECT\x10\x02\x12\b\n" +
	"\x04ROOT\x10\x03\x12\x14\n" +
	"\x10SEGMENT_AND_ROOT\x10\x04\x12\v\n" +
	"\aTO_ROOT\x10\x0529\n" +
	"\x06PubSub\x12/\n" +
	"\aChannel\x12\x0e.proto.Message\x1a\x0e.proto.Message\"\x00(\x010\x01B\x11Z\x0fplatforme/protob\x06proto3"

var (
	file_proto_pubsub_proto_rawDescOnce sync.Once
	file_proto_pubsub_proto_rawDescData []byte
)

func file_proto_pubsub_proto_rawDescGZIP() []byte {
	file_proto_pubsub_proto_rawDescOnce.Do(func() {
		file_proto_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pubsub_proto_rawDesc), len(file_proto_pubsub_proto_rawDesc)))
	})
	return file_proto_pubsub_proto_rawDescData
}

var file_proto_pubsub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_pubsub_proto_goTypes = []any{
	(PubSubScope)(0),              // 0: proto.PubSubScope
	(*Message)(nil),               // 1: proto.Message
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_pubsub_proto_depIdxs = []int32{
	0, // 0: proto.Message.scope:type_name -> proto.PubSubScope
	2, // 1: proto.Message.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: proto.PubSub.Channel:input_type -> proto.Message
	1, // 3: proto.PubSub.Channel:output_type -> proto.Message
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pubsub_proto_init() }
func file_proto_pubsub_proto_init() {
	if File_proto_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pubsub_proto_rawDesc), len(file_proto_pubsub_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pubsub_proto_goTypes,
		DependencyIndexes: file_proto_pubsub_proto_depIdxs,
		EnumInfos:         file_proto_pubsub_proto_enumTypes,
		MessageInfos:      file_proto_pubsub_proto_msgTypes,
	}.Build()
	File_proto_pubsub_proto = out.File
	file_proto_pubsub_proto_goTypes = nil
	file_proto_pubsub_proto_depIdxs = nil
}
